var limitset=document.getElementById("limitset");
// var ctcollect=document.getElementById("ctcollect");
var ctquery=document.getElementById("ctquery");
// var ctSecondExam=document.getElementById("ctSecondExam");
var financeExam=document.getElementById("financeExam");
// var financeSecondExam=document.getElementById("financeSecondExam");
var qyInforManage=document.getElementById("qyInforManage");
var qyUserManage=document.getElementById("qyUserManage");
var bankManage=document.getElementById("bankManage");
var sureInforManage=document.getElementById("sureInforManage");
// var supply=document.getElementById("supply");

var limitsetPage=document.getElementById("limitset-page");
// var ctcollectPage=document.getElementById("ctcollect-page");
var ctqueryPage=document.getElementById("ctquery-page");
// var ctSecondExamPage=document.getElementById("ctSecondExam-page");
var financeExamPage=document.getElementById("financeExam-page");
// var financeSecondExamPage=document.getElementById("financeSecondExam-page");
var qyInforManagePage=document.getElementById("qyInforManage-page");
var qyUserManagePage=document.getElementById("qyUserManage-page");
var bankManagePage=document.getElementById("bankManage-page");
var sureInforManagePage=document.getElementById("sureInforManage-page");
// var supplyPage=document.getElementById("supply-page");

limitset.onclick=function(){
	limitsetPage.style.display="block";
	// ctcollectPage.style.display="none";
	ctqueryPage.style.display="none";
	// ctSecondExamPage.style.display="none";
	financeExamPage.style.display="none";
	//financeSecondExamPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	// supplyPage.style.display="none";
}
// ctcollect.onclick=function(){
// 	limitsetPage.style.display="none";
// 	// ctcollectPage.style.display="block";
// 	ctqueryPage.style.display="none";
// 	// ctSecondExamPage.style.display="none";
// 	financeExamPage.style.display="none";
// 	//financeSecondExamPage.style.display="none";
// 	qyInforManagePage.style.display="none"
// 	qyUserManagePage.style.display="none";
// 	bankManagePage.style.display="none";
// 	sureInforManagePage.style.display="none";
// 	// supplyPage.style.display="none";
// }
ctquery.onclick=function(){
	limitsetPage.style.display="none";
	// ctcollectPage.style.display="none";
	ctqueryPage.style.display="block";
	// ctSecondExamPage.style.display="none";
	financeExamPage.style.display="none";
	//financeSecondExamPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	// supplyPage.style.display="none";
}
// ctSecondExam.onclick=function(){
// 	limitsetPage.style.display="none";
// 	// ctcollectPage.style.display="none";
// 	ctqueryPage.style.display="none";
// 	// ctSecondExamPage.style.display="block";
// 	financeExamPage.style.display="none";
// 	//financeSecondExamPage.style.display="none";
// 	qyInforManagePage.style.display="none"
// 	qyUserManagePage.style.display="none";
// 	bankManagePage.style.display="none";
// 	sureInforManagePage.style.display="none";
// 	// supplyPage.style.display="none";
// }

financeExam.onclick=function(){
	limitsetPage.style.display="none";
	// ctcollectPage.style.display="none";
	ctqueryPage.style.display="none";
	// ctSecondExamPage.style.display="none";
	financeExamPage.style.display="block";
	//financeSecondExamPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	// supplyPage.style.display="none";
}

qyInforManage.onclick=function(){
	limitsetPage.style.display="none";
	// ctcollectPage.style.display="none";
	ctqueryPage.style.display="none";
	// ctSecondExamPage.style.display="none";
	financeExamPage.style.display="none";
	//financeSecondExamPage.style.display="none";
	qyInforManagePage.style.display="block"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	// supplyPage.style.display="none";
}
qyUserManage.onclick=function(){
	limitsetPage.style.display="none";
	// ctcollectPage.style.display="none";
	ctqueryPage.style.display="none";
	// ctSecondExamPage.style.display="none";
	financeExamPage.style.display="none";
	//financeSecondExamPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="block";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	// supplyPage.style.display="none";
}
bankManage.onclick=function(){
	limitsetPage.style.display="none";
	// ctcollectPage.style.display="none";
	ctqueryPage.style.display="none";
	// ctSecondExamPage.style.display="none";
	financeExamPage.style.display="none";
	//financeSecondExamPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="block";
	sureInforManagePage.style.display="none";
	// supplyPage.style.display="none";
}
sureInforManage.onclick=function(){
	limitsetPage.style.display="none";
	// ctcollectPage.style.display="none";
	ctqueryPage.style.display="none";
	// ctSecondExamPage.style.display="none";
	financeExamPage.style.display="none";
	//financeSecondExamPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="block";
	// supplyPage.style.display="none";
}
// supply.onclick=function(){
// 	limitsetPage.style.display="none";
// 	// ctcollectPage.style.display="none";
// 	ctqueryPage.style.display="none";
// 	// ctSecondExamPage.style.display="none";
// 	financeExamPage.style.display="none";
// 	//financeSecondExamPage.style.display="none";
// 	qyInforManagePage.style.display="none"
// 	qyUserManagePage.style.display="none";
// 	bankManagePage.style.display="none";
// 	sureInforManagePage.style.display="none";
// 	// supplyPage.style.display="block";
// }
