var ctfinance=document.getElementById("ctfinance");
var ctsign=document.getElementById("ctsign");
var cttransfer=document.getElementById("cttransfer");
var ctquery=document.getElementById("ctquery");
var qyInforManage=document.getElementById("qyInforManage");
var qyUserManage=document.getElementById("qyUserManage");
var bankManage=document.getElementById("bankManage");
var sureInforManage=document.getElementById("sureInforManage");
var supply=document.getElementById("supply");

var ctfinancePage=document.getElementById("ctfinance-page");
var ctsignPage=document.getElementById("ctsign-page");
var cttransferPage=document.getElementById("cttransfer-page");
var ctqueryPage=document.getElementById("ctquery-page");
var qyInforManagePage=document.getElementById("qyInforManage-page");
var qyUserManagePage=document.getElementById("qyUserManage-page");
var bankManagePage=document.getElementById("bankManage-page");
var sureInforManagePage=document.getElementById("sureInforManage-page");
var supplyPage=document.getElementById("supply-page");

ctfinance.onclick=function(){
	ctfinancePage.style.display="block";
	ctsignPage.style.display="none";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="none";
}
ctsign.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="block";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="none";
}
cttransfer.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="none";
	cttransferPage.style.display="block";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="none";
}
ctquery.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="none";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="block";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="none";
}
qyInforManage.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="none";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="block"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="none";
}
qyUserManage.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="none";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="block";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="none";
}
bankManage.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="none";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="block";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="none";
}
sureInforManage.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="none";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="block";
	supplyPage.style.display="none";
}
supply.onclick=function(){
	ctfinancePage.style.display="none";
	ctsignPage.style.display="none";
	cttransferPage.style.display="none";
	ctqueryPage.style.display="none";
	qyInforManagePage.style.display="none"
	qyUserManagePage.style.display="none";
	bankManagePage.style.display="none";
	sureInforManagePage.style.display="none";
	supplyPage.style.display="block";
}
